### ISSUE TITLE
hey can anybody make a dockerfile for windows export? label:question 

### ISSUE THREAD

**Issue by konos93** [ScanTailor-Advanced/scantailor-advanced#46]
for linux ubuntu i used this and worked https://github.com/ryanfb/docker_scantailor/blob/master/Dockerfile.advanced

**Comment by FriedrichFroebel** [comment]
The file you link seems to have nothing to do with ScanTailor or similar at all, but is used for vulnerability detection only. Why would you use an application running in Docker on Windows when there is a native Windows executable as for ScanTailor?

**Comment by konos93** [comment]
> The file you link seems to have nothing to do with ScanTailor or similar at all, but is used for vulnerability detection only. Why would you use an application running in Docker on Windows when there is a native Windows executable as for ScanTailor?

my mistake i corrected the link

**Comment by konos93** [comment]
i am trying to build a combination on scantailor advanced and experimental because i want advanced with match size scale margins from experimental

**Comment by FriedrichFroebel** [comment]
Have you tried using the above Dockerfile on Windows? Judging from articles like https://dev.to/darksmile92/run-gui-app-in-linux-docker-container-on-windows-host-4kde, this should be possible in theory. (Disclaimer: I have never used Docker on Windows.)
