### ISSUE TITLE
[Feature request] KMeans?

### ISSUE THREAD

**Issue by zvezdochiot** [ScanTailor-Advanced/scantailor-advanced#65]
Hi @mara004 , @lightsilverberryfox , @vigri .

Use KMeans instead of Posterization? And the number of colors instead of the level of posterization?

See [noteshrink-c](https://github.com/ImageProcessing-ElectronicPublications/noteshrink-c).

| Origin | KMeans (noteshrink) |
| --- | --- |
| full colors | 6 colors |
| ![sample](https://raw.githubusercontent.com/ImageProcessing-ElectronicPublications/noteshrink-c/master/images/test.jpg) | ![noteshrik](https://raw.githubusercontent.com/ImageProcessing-ElectronicPublications/noteshrink-c/master/images/testout.png) |

**Comment by mara004** [comment]
Hi @zvezdochiot,

you don't need to ping me for general topics that do not actually target myself (e.g. in contrast to questions/replies addressed at me specifically). I configure notification events to my liking through GH's watch feature.
I'm not an STA developer, merely a user, and only know Python, not C++.

Thanks.

**Comment by zvezdochiot** [comment]
Resolved. [STEX: 0.2023.08.21: kmeans](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/releases/tag/0.2023.08.21).
