### ISSUE TITLE
Brother flatbed scanner's TIFs cannot be loaded

### ISSUE THREAD

**Issue by ireun** [ScanTailor-Advanced/scantailor-advanced#79]
Hi!

Test file:
[test.zip](https://github.com/ScanTailor-Advanced/scantailor-advanced/files/12542927/test.zip)

This file was produced using Brother MFC-L6900DW. Seems like no TIF from this printer can be red by STA. I've tried greyscale, colour, single-page-tiff and multi-page-tiff (STA recognizes that it is multi-page but does not read the page itself)

All I'm getting is that file cannot be loaded:
![image](https://github.com/ScanTailor-Advanced/scantailor-advanced/assets/695818/0449a0f6-756b-436c-b96d-fec15efad486)

IrfanView Info:
![image](https://github.com/ScanTailor-Advanced/scantailor-advanced/assets/695818/bad50932-5f70-4078-a770-037931d7de2d)

**Comment by trufanov-nok** [comment]
I'm able to open it on Linux machine...   
I would suspect that Win version of STA is built with too old libjpeg or libtiff versions and this is a cause of the problem. But can't launch a Win version to doublecheck.

**Comment by darnn** [comment]
Opens for me in scantailor-advanced_1.0.18-qt5_win64_epdb, I forget whose build it is.

**Comment by darnn** [comment]
> Hi @darnn .
> 
> See https://github.com/ImageProcessing-ElectronicPublications/scantailor-advanced/releases :
> 
>     * 1.0.19-qt5_win64 (aka 1.0.18-epdbtaed)
> 
>     * 1.0.18-qt5_win64_epdbta
> 
>     * 1.0.18-qt5_win64_epdb

Hi! I have indeed seen those, I just think I had some trouble with 
ScanTailor-Advanced-1.0.19.win-x64.zip from there and ended up reverting to the one I was using. But 
scantailor-advanced_1.0.19-qt5_win64.zip seems to be working fine. Also, that TIF file doesn't open in the former, but opens in the latter.

**Comment by ireun** [comment]
Hi @zvezdochiot, I've tried the QT5 version `scantailor-advanced_1.0.19-qt5_win64.zip` and it indeed works fine, thanks!

**Comment by zvezdochiot** [comment]
Hi all.

:information_source: Mantainers made the wrong bet on Qt6, forgetting that the end user does not need an experimental sample, but a proven working tool.

**Comment by ireun** [comment]
Don't worry, thanks for maintaining it! Kind regards!
