### ISSUE TITLE
Feature Request: Binarization Algorithms

### ISSUE THREAD

**Issue by H748** [ScanTailor-Advanced/scantailor-advanced#8]
Hi,
I use STA on a regular basis to edit archival research and am very happy to see that is maintained again. 
I think it would be great, if STA offered more and some of the improved binarization algorithms like WAN or ISauvola. Often, the images I have to work with have subpar quality and some of the new and improved algorithms would be greatly welcomed.

Anyway: Thanks for maintaining the project!

**Comment by zvezdochiot** [comment]
Hi @lightsilverberryfox .

Interested in the possibility of mixing canny into the original image before threshold:
```
Ic = (1.0-k) * I + k * I * (255 - canny) / 255

or

Ic = I * (255 -  255 * k * canny) / 255

where:
  k = { 0.0 (no canny) .. 1.0 (add 100% canny) }
  canny = image{ 0 (no edge) .. 255 (edge) }
```

Mixing canny allows you to:
1. keep tails and jumpers of individual letters.
2. keep the original halftone pattern of the images.

**Comment by vigri** [comment]
@zvezdochiot can I close this one? 
As to my understanding, this is "fixed" with #48

**Comment by zvezdochiot** [comment]
Hi @vigri .

This is not my issue. But I think it's been resolved.

**Comment by vigri** [comment]
Thanks for your response.

I'll close this one.

@H748 If you think your request is still not fulfilled, please feel free to open a new issue.
